-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPwGKknJVJqcOcdv4
OG7y1/wZ6+uEF/ZyeuNP0DDPsI+gCgYIKoZIzj0DAQehRANCAAQDsUD63Ci12t7N
DdMK2utvmleJ0StS3ByIQdTv0eIxwwtBtPJreJqrQcHjRwjgAnN4rBGl8Cmn6B50
Y7bIFqfT
-----END PRIVATE KEY-----